# Generated by Django 2.1.7 on 2019-03-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sname', models.CharField(max_length=10)),
                ('Sid', models.CharField(max_length=20)),
                ('Sex', models.CharField(max_length=4)),
                ('Department', models.CharField(max_length=100)),
                ('Major_class', models.CharField(max_length=100)),
                ('Phone_number', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Declaration', models.CharField(max_length=200)),
                ('Resume', models.CharField(max_length=100)),
                ('Comprehension', models.CharField(max_length=100)),
            ],
        ),
    ]
